# Generated by Django 2.1.5 on 2022-03-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='nickname')),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='email')),
                ('token', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
