# Generated by Django 2.1.5 on 2022-03-19 21:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=128)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='target',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
