# Generated by Django 2.1.5 on 2022-03-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20220319_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(max_length=64),
        ),
    ]
